version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "4800:4800"
    networks:
      - mean-network

  frontend:
    build: ./frontend
    ports:
      - "4200:80"
    networks:
      - mean-network

networks:
  mean-network:
