# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Optionally, you can copy initialization scripts if needed
# COPY ./init-mongo.js /docker-entrypoint-initdb.d/
